### ISSUE TITLE
CRUD Example

### ISSUE THREAD

**Issue by rsvancara** [rodrigogs/nodejs-web-jade-scaffold#3]
Do you have an example of using this framework with a CRUD example.  Specifically I am trying to list records from a collection in mongodb and I can not figure out how to setup a service method to provide a list.  Sorry, I am new to Node.JS and I just need an example of how to get started.

**Comment by rodrigogs** [comment]
Well... If you check [here](https://github.com/rodrigogs/nodejs-web-jade-scaffold/blob/master/app/controllers/api/user.js), I'm extending class Crud in my User class, and it gives me a ready to use CRUD. I'm using a [module](https://github.com/danielrohers/web-crud) made by a friend of mine, that gives me that Crud class, so I can just extend and override its methods if I need.

Checking this module implementation should remedy your question. If not, just let me know ;)

**Comment by danielrohers** [comment]
Hey @rsvancara, you can check how to use the CRUD [here](https://github.com/danielrohers/web-crud#controllerfoojs). You can override the CRUD methods as in the example and recalling using `super`.

**Comment by rodrigogs** [comment]
closed due to inactivity
